### ISSUE TITLE
Steam Achievement Notifier.exe no found

### ISSUE THREAD

**Issue by sxocker** [SteamAchievementNotifier/SteamAchievementNotifier#1]
I have done all the steps shown, but I did not see the .exe not showing up on my desktop

**Comment by SteamAchievementNotifier** [comment]
Hello,

Did the Powershell window appear to input your Steam API Key etc? If you've filled all of this in, you can find the main script (_systray.ps1_) by going to `C:\Users\<username>\AppData\Local\SteamAchievementNotifier`. Once there, right-click _systray.ps1_ > _Send To_ > _Desktop_.

Let me know if you have any further issues after doing this.

Thanks!

**Comment by SteamAchievementNotifier** [comment]
Hi again,

If you still need help, [Version 1.4](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/releases/tag/1.4) has now been released - please give this version a try as it should be simpler to set up. Feel free to open a new issue if you're still having problems.

Thanks!
