### ISSUE TITLE
App is using all my CPU after a while

### ISSUE THREAD

**Issue by y0LAs** [SteamAchievementNotifier/SteamAchievementNotifier#11]
Hello,
I noticed that after the app is running for a while (I'd say an hour of two) the app is eating my CPU resources like crazy, making me wonder if it is mining crypto or something... 
While it's unlikely for an open source app, I come back to you so you can have notice of this issue.

![Screenshot (71)](https://user-images.githubusercontent.com/15331126/156961039-c8ccdf23-1d89-44a6-9074-a88ad58a7aea.png)
![Screenshot (69)](https://user-images.githubusercontent.com/15331126/156961049-aebe4488-75d4-4e70-a180-3f15cb498ab8.png)

**Comment by SteamAchievementNotifier** [comment]
Hey @y0LAs, sorry to hear you're having issues with the app!

I haven't personally seen (or had reports from other users) that CPU usage is abnormally high in general use of the app, but in dev/testing, there were a few instances where either garbage collection did not initialise properly, or more Electron processes were spawned than intended, but this is usually resolved by quitting/restarting the app.

I will be looking into releasing an incremental update to ensure that resources are being properly disposed of, which will reduce any abnormal CPU/memory impact on the system, but in the meantime, if you notice any high numbers here, an app restart should fix this issue.

Sending a large amount of test notifications to the queue could also cause high resource usage, and in some instances, these extra notification processes may potentially be improperly disposed of. I'll be looking into replicating this on other hardware and see if I can mitigate some of the resource overhead.

Also, full disclosure: I have absolutely zero interest in crypto/mining in general, let alone using my app to deceive other users - if you're unsure, please feel free to check through the app's files in the repo to confirm this!

Please let me know if you're still having issues with this after restarting the app. You can also join the Discord if you need any further help!

Thanks!

**Comment by y0LAs** [comment]
Hi, thank you for your response!
Sorry for the mining thinking, but I was just sharing what other users may think :)
So yes, I actually do frequent tests notifications, and it may indeed be the cause of this CPU usage :)
Thank you again, I really appreciate your app! :)
