### ISSUE TITLE
App not working if Steam is in Offline Mode

### ISSUE THREAD

**Issue by y0LAs** [SteamAchievementNotifier/SteamAchievementNotifier#12]
H! 
(Not sure I'm posting it in the right place)
Really love the app, **but it doesn't work in offline mode**.
I personally use offline mode to allow ASF (Archi's SC Farm) to unlock trading cards for other games while I'm playing.
**I hope it is possible and that you will unlock Steam Achievement Notifier in offline mode.**
Anyway, thank you very much, this really enhances my gaming experience.
Have a great day :)

Edit : I had my response, do you think it will be possible in the future or is it hopeless?
https://discord.com/channels/903745038826229762/903745565391741008/918437141892182066

**Comment by SteamAchievementNotifier** [comment]
Hey again, @y0LAs!

Currently, Steam Achievement Notifier uses the Steam Web API to track your achievement stats. If Steam is in Offline mode, your achievement stats will not be updated online, and therefore cannot be tracked by Steam Achievement Notifier (until Steam is set back to Online mode).

In the future, I am hoping to update the app's backend to use SteamWorks, which would be faster at retrieving stats and would allow for offline tracking, but unfortunately, at the moment, this isn't possible using the current Steam Web API implementation.

Regarding your edit, the app **will** now track achievements if your status is set to "Invisible" in Friends & Chat, but only if Steam is in Online mode.

Thank you for checking out the app and I'm glad you're enjoying it!

**Comment by y0LAs** [comment]
Thank you! Glad it will come to day some time in the future! :)
