### ISSUE TITLE
Elden Ring fullscreen alt-tab

### ISSUE THREAD

**Issue by aduranti23** [SteamAchievementNotifier/SteamAchievementNotifier#14]
I was playing Elden Ring, and I've unlocked an achivement, but the game were reduced to icon. The game was fullscreen.

**Comment by SteamAchievementNotifier** [comment]
Hey @aduranti23,

At the moment, notifications can't be shown over games running in Fullscreen mode (only Borderless/Windowed mode will allow notifications to be shown on top of them). I'm working on adding Fullscreen support in a future release!

Thanks!
