### ISSUE TITLE
Screenshots Blank White

### ISSUE THREAD

**Issue by xyifer12** [SteamAchievementNotifier/SteamAchievementNotifier#15]
Issue: Automatic notification screenshots are 95-100% white.

Tested:
Hide Steam Achievement Notification checked and unchecked, makes no difference.
Path changed from C:\Users\Xyifer\Pictures\GameAchievements to C:\Users\Xyifer\Pictures\Trophies, made no difference.
Disable Hardware Acceleration checked and unchecked, makes no difference.
Closed MSI Afterburner and RTSS, makes no difference. 
Disabled Special K, makes no difference.

Additional Information:
I'm using SAN 1.83, screenshot previews are enabled for the notification popups. The popup ingame shows the screenshot correctly, it's just the saved file that is faulty. I run Windows 10 Pro 21H2, x64. GeForce Experience is always passively recording. 
The following images are examples of Civilization 5 and Elden Ring screenshots.

![Kamikaze Attack](https://user-images.githubusercontent.com/33806276/168774896-44fb7666-d6ce-4e42-aef2-5bc5618a6355.png)
![Legendary Sorceries and Incantations](https://user-images.githubusercontent.com/33806276/168774905-29d63f3c-a7a5-4e68-8427-2440694dacb6.png)

**Comment by SteamAchievementNotifier** [comment]
Hey @xyifer12,

The only way I've been able to replicate this issue in the past is to have something "interrupt" the screenshot painting function (which would include things like dialog boxes/alt-tabbing out of games/focusing other windows etc). However, if this is happening just during normal gameplay, I'll have to look into a proper solution.

That said, Version 1.84 includes some changes to the "Save Screenshots with Overlay" option, and should be released within the next few days. If you could re-test once released and let me know whether you're still having this issue, I will look into it further.

Thanks!

**Comment by xyifer12** [comment]
1.84 has changed the problem. Screenshots now save, but the images use an incorrect notification style.

This is the incorrect style used in screenshots:
![Dead Eye](https://user-images.githubusercontent.com/33806276/169353294-cc21ab89-eb5b-4443-9641-004344cd20c1.png)

This is an example of the style SAN is currently set to use:
![example2](https://user-images.githubusercontent.com/33806276/169353318-585e90ba-8ab9-4779-afaa-8ce3629f389b.png)

**Comment by xyifer12** [comment]
Text color is indeed set to white for my rare achievements, which is what the screenshot is from. I have unlocked 5 more achievements in Elden Ring with 4 working correctly, however one screenshot is presenting the original issue for no apparent reason.

Here are automatic screenshots, one normal and one errored:
![Legendary Talismans](https://user-images.githubusercontent.com/33806276/169397890-045fae54-7ad5-43ea-9454-85c497089fb2.png)

![Legendary Sorceries and Incantations](https://user-images.githubusercontent.com/33806276/169397880-3c595e81-3b96-41ee-8453-9c586e0b4c02.png)
.

**Comment by SteamAchievementNotifier** [comment]
Hey again @xyifer12,

The second screenshot looks like it might have been taken in Version 1.83 (hence why you would see the return of the white screen issue, along with the right-hand placement of the notification). If you could do the following and test whether the issue still occurs, it would help me out a lot with troubleshooting!

1. If you have a Desktop shortcut to run Steam Achievement Notifier, delete it, run **Version 1.84** (_via **SANLauncherV1.84.exe**_) and re-add the shortcut using the "**Create Desktop Shortcut**" option in the Settings menu.
2. Open the Start menu and type `%localappdata%`, then press Enter (this will open your **LocalAppData** folder). In this folder, open the "**Steam Achievement Notifier (V1.8)**" folder - if "**SteamAchievementNotifierV1.83.exe**" is present in this folder, delete it.

If the same issue still occurs after double-checking Version 1.84 is running, I will look to push out a new automatic app revision (when I get some time) to hopefully resolve it.

Thanks!

**Comment by xyifer12** [comment]
SAN 1.83 was indeed present in my AppData\Local\Steam Achievement Notifier (V1.8) directory. I've deleted the EXE and restarted my computer, leaving only 1.84 in that directory. Thank you for your help, I will keep an eye out for any new issues but I believe this one is solved.
