### ISSUE TITLE
Uncaught Exception: SyntaxError: Unexpected Token

### ISSUE THREAD

**Issue by mainmango** [SteamAchievementNotifier/SteamAchievementNotifier#16]
I'm receiving the error below when launching the app. Any suggestions?

A JavaScript error occured in the main process

Uncaught Exception:
SyntaxError: Unexpected token

**Comment by SteamAchievementNotifier** [comment]
Hey @mainmango,

As discussed on Discord (and for anyone else running into this issue), if this error prevents the app from starting, please do the following:

1. Open the Start Menu, type: `%localappdata%` and press Enter.
2. In this folder, find the `Steam Achievement Notifier (V1.8)` folder.
3. (Optional) Open the "store" folder and copy "config.json" to back up your user settings.
4. Delete the entire `Steam Achievement Notifier (V1.8)` folder (in `%localappdata%`).
5. Run "SANLauncher1.84.exe" again to regenerate the folder.
6. (Optional) Re-open `%localappdata%\Steam Achievement Notifier (V1.8)\store` and paste your old "config.json" file to restore your previous settings.

Thanks!
