### ISSUE TITLE
French grammar

### ISSUE THREAD

**Issue by ghost** [SteamAchievementNotifier/SteamAchievementNotifier#17]
Hello, first of all I love what you did with Steam Achievement Notifier. It works perfectly for me and it made me enjoy achievements even more ! Just a little something that bothers me as a native french speaker, the notification ''Achievement unlocked'' is translated as ''Succès dévérouillé''. It's actually written this way : ''Succès déverrouillé''.

That's all, thanks in advance !

**Comment by SteamAchievementNotifier** [comment]
Hey @Syl247, thank you for checking it out and I'm glad you're enjoying it!

Thanks for letting me know - I'll revise the translation in the next app revision. If you find any other translations you think need changing, you can let me know either here or on Discord.

Thanks!
