### ISSUE TITLE
Suddenly not showing on games screen

### ISSUE THREAD

**Issue by Beaudatious** [SteamAchievementNotifier/SteamAchievementNotifier#25]
First of all, I will appreciate the fact you made this, its much more satisfying than a steam pop up in the corner, I would donate you if I could afford it in my current situation, absolutely worth it. 

My missus and I are both having issues with it showing up on the game, it shows up behind. It was working before and I have tried changing it to borderless window and even back to fullscreen but nothing. It'll show up on windowed but I dont play games like that. Could you help us with this issue?

Thank you

**Comment by SteamAchievementNotifier** [comment]
Hey @Beaudatious - thank you for checking it out and I'm glad you're enjoying it!

Are you having this issue with one game in particular, or multiple games? The notification is set to be an Always-On-Top window, so as long as you don't have any other window preventing it from being displayed on top - i.e. a game window set to Fullscreen/Exclusive Fullscreen mode - the notification should be able to show over anything else.

If this issue occurs in one particular game and doesn't work on any other mode outside of "Windowed", you could try using [Borderless Gaming](https://github.com/Codeusa/Borderless-Gaming/releases/tag/9.5.6) to maximise it to Borderless Fullscreen.

Thanks!

**Comment by SteamAchievementNotifier** [comment]
Hey again @Beaudatious,

As I haven't had a response to this, I will close this issue. If you're still having problems, please let me know!

Thanks!
