### ISSUE TITLE
Unable to recognize steam user

### ISSUE THREAD

**Issue by sleepsn** [SteamAchievementNotifier/SteamAchievementNotifier#26]
I am a user in China. Because of the network shielding in China, sometimes can't correctly identify the user or game status. I don't know what kind of network address Steam uses, but I can't always connect smoothly in China. It would be better if there was a function to recheck the network. This is translated with translation software

**Comment by SteamAchievementNotifier** [comment]
Hey @sleepsn,

As far as I am aware, the Steam Web API (that Steam Achievement Notifier uses) does not have any kind of throttling or rate-limiting behaviour based on region, and as long as your connection is stable, it should work without issue.

If you find that you are frequently disconnected, please check the console for any errors:

> Focus the main app window, then press `CTRL` + `Shift` + `i` to bring up the DevTools window. From there, click `>>` at the top of the page (next to the `Elements` tab), and select `Console` from the dropdown menu.

Thanks!

**Comment by SteamAchievementNotifier** [comment]
Hey @sleepsn,

As I haven't had a response to this, I will close this issue. If you're still having problems, please let me know!

Thanks!
