### ISSUE TITLE
sad for batman ):

### ISSUE THREAD

**Issue by darkerraven** [SteamAchievementNotifier/SteamAchievementNotifier#27]
![batman](https://user-images.githubusercontent.com/115076107/194034967-62d5355f-0516-497a-a95c-06083af67a5b.png)

**Comment by SteamAchievementNotifier** [comment]
Hey @darkerraven,

Apologies for the (very) late response to this! The GOverlay application (that powers SAN's Fullscreen notifications) has recently been updated to provide more detailed debugging information, and is available in the most recent Beta Channel App Revision (which will automatically be available for download the next time you launch SAN).

In terms of required information, if you're still having issues with a particular game, please do the following:

>- Run a game with SAN set to **Fullscreen** mode (to enable this setting in the newest version [BETA 0.6], click the **Borderless/Fullscreen** toggle button in the top-right corner of the main app window)
>- If you receive this error, open the Start Menu and type/paste `%localappdata%\Steam Achievement Notifier (V1.8)\store` and press Enter
>- Find `fsdebug.txt` and upload it here

Alternatively, I have also created [GOverlayDebug](https://github.com/Jackson0ne/GOverlayDebug/releases/tag/v1.0) to provide a more user-friendly debugging experience. Just follow the instructions on the release page to test it out.

Thanks!

**Comment by SteamAchievementNotifier** [comment]
Closing issue as **Fullscreen** mode for V1.84's Beta Channel will not be updated until release of next major version.
