### ISSUE TITLE
Kingdoms of Amalur: Re-Reckoning 

### ISSUE THREAD

**Issue by Zipmasterflexx** [SteamAchievementNotifier/SteamAchievementNotifier#29]
Hello, great tool you build there. I wanted to try it for KOA , but sadly the overlay/trophy-notification/tracking-notification does  not show (only my custom sound plays.) (Fullscreen / Borderless / Widowed ) all tested -  Nvidia Overlay ON/OFF - Reshade ON/OFF). I tested it with Tekken 7 , it works flawlessly. So i guess it has something to do with specificly KOA or how its programmed or something like that. Do you have any tips for that? did you encounter a game where its the same and you found a workaround i could try?

**Comment by SteamAchievementNotifier** [comment]
Hey @Zipmasterflexx,

I had a look at the Store page for Kingdoms of Amalur, and it seems to be running on DirectX 10/11, so theoretically, it shouldn't have any issues displaying windows on top when set to Borderless Fullscreen mode in-game.

If there are no other in-game display options to test with, I recommend checking out [Borderless Gaming](https://github.com/Codeusa/Borderless-Gaming/releases/tag/9.5.6) to ensure the window is actually Borderless.

Let me know if you have any further issues with this game in particular.

Thanks!

**Comment by Zipmasterflexx** [comment]
I should have wrote this earlier. it just worked the next day. i have to use borderless fullscreen mode (only the ingame option, not even the programm) and it just worked. it 100% did not work the day before, even with borderless fullscreen. so yea . thanks for the answer but in the end : IT.JUST.WORKS.

**Comment by SteamAchievementNotifier** [comment]
Hey again @Zipmasterflexx,

Glad to hear it's working for you now! Not sure why that would have happened, but as long as the issue is resolved for now, let me know if you have any further issues.

Thanks!
