### ISSUE TITLE
Error: "fullscreen.json" caused an error on load: "SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by Vervaticus** [SteamAchievementNotifier/SteamAchievementNotifier#31]

**Comment by SteamAchievementNotifier** [comment]
Hey @Vervaticus,

As discussed on Discord, you can delete `fullscreen.json` from `%localappdata%\Steam Achievement Notifier (V1.8)\store`, then relaunch the app to resolve this issue. SAN will regenerate this file upon next launch.

Thanks!
