### ISSUE TITLE
severals problems

### ISSUE THREAD

**Issue by starkaris** [SteamAchievementNotifier/SteamAchievementNotifier#32]
Hello, so I have several problems. The first is that when I set notifications to "audio mode only except steam", the notification also appears and the sound doesn't always appear. My second problem is that when I put the notifications, they never place themselves in the center of the game as I want but stay in the bottom right corner by default. I also noticed that sometimes the notification launches "out of the game" on my desktop but not in the game. 
Do you have any solutions? Thank you
The game tested with is Jedi: fallen order

**Comment by SteamAchievementNotifier** [comment]
Issue being tracked on Discord - closing.
