### ISSUE TITLE
Unable to open app

### ISSUE THREAD

**Issue by sleepsn** [SteamAchievementNotifier/SteamAchievementNotifier#35]
It seems that because I deleted it by mistake, I cannot open the application again. Even if I reinstall it, I cannot see it in the taskbar, but I can see it in the task manager
![QQ图片20230102195206](https://user-images.githubusercontent.com/110544624/210227879-2a325972-669c-4728-9d33-b9887f2411a5.png)
![QQ截图20230102195224](https://user-images.githubusercontent.com/110544624/210227881-03c80632-e8f6-4113-8d96-a30e1d316cf8.png)

**Comment by sleepsn** [comment]
![image](https://user-images.githubusercontent.com/110544624/210232214-a58e2260-6a52-4e2b-83f1-f5c4eb82e1ad.png)
Moved Permanently. Redirecting to https://raw.githubusercontent.com/SteamAchievementNotifier/SteamAchievementNotifier/ec7f8a208e4f69ca0566f7fef25184e351209287/index.html

**Comment by SteamAchievementNotifier** [comment]
Issue resolved via Discord - closing.
