### ISSUE TITLE
Achievement Notification pop-up not showing

### ISSUE THREAD

**Issue by LukyMore** [SteamAchievementNotifier/SteamAchievementNotifier#37]
Hello, I have tried everything that I could, I checked my Steam64ID several times, I created a new Steam API Key with the domain name "SteamAchievementNotifier", copied the Steam API Key and it's still not working. I have Game Details enabled in my Steam Profile, what should I do? When I get the achievement on Steam, it doesn't pop-up or play anything in the SAN App (I am playing on borderless so I should see the notification even if the audio was broken)

Please help me...

**Comment by SteamAchievementNotifier** [comment]
Hey @LukyMore,

Sorry to hear you're having issues - please double-check the following:

> **API Key**:
> - Make sure you've saved the value to your config file using the **Save** button

> **Steam64ID**:
> - As above, make sure you've saved the value using the **Save** button
> - Ensure SAN is tracking your profile - search using your Steam profile URL on https://steamid.io/ to make sure it's not returning another user's credentials with a similar Steam alias
> - Ensure that you're using the correct value here - using https://steamid.io/, you should be entering the **steamid64** value (which should only be numbers), NOT any other value listed on the page

If you're positive that these details are correct, open the **DevTools** window and check the **Console** tab for any errors.

> To open the **Console**:
> 1) Click the **Open DevTools** button in the Settings menu (in the very bottom-right corner, to the right of the **App Revision** number)
> 2) Make sure the **Console** tab is selected (`>>` next to `Elements` at the top of the window > `Console`)

Thanks!

**Comment by LukyMore** [comment]
![e5b449a5d602c92bcc973bbe93b4899f](https://user-images.githubusercontent.com/79324763/216832580-66b333f8-91a7-4144-993b-f42c09efc0ee.png)

I have found this in the console, what should I do? Everything is set correctly.

**Comment by SteamAchievementNotifier** [comment]
Hey again @LukyMore,

Seems like Steam had some server issues earlier today, and a 500 error means there's an issue on Steam's side, so I would probably give it a while and try SAN again. If you keep getting the same error, let me know 👍

Thanks!

**Comment by SteamAchievementNotifier** [comment]
Hey @LukyMore,

Have you attempted to use SAN since? If so, does it appear to be working now?

Thanks!

**Comment by LukyMore** [comment]
Hello, sorry but I am currently in a place with no internet connection (using mobile data now) So I can't test it out, but tomorrow I will let you know once I arrive at home. Btw, it started working on Sunday night right before I left so maybe it will work even tomorrow.

**Comment by LukyMore** [comment]
It seems to be working as intended now, thank you.
