### ISSUE TITLE
I'm having trouble doing both the api key and the steam 64 id

### ISSUE THREAD

**Issue by bordeyishome** [SteamAchievementNotifier/SteamAchievementNotifier#38]
I put in my api key and steam 64 id and they both did not work. Can you like make a video or something to show if I did something wrong?

**Comment by SteamAchievementNotifier** [comment]
Hey @bordeyishome,

Please follow these instructions to ensure you've entered the right information into SAN:

> **API KEY**:
> -
> - Go to https://steamcommunity.com/login/home/?goto=%2Fdev%2Fapikey
> - Sign in with your Steam account (*this is an official Valve website, so you don't need to worry!*)
> - When asked to enter a **domain name**, you can enter *any* website address (*e.g. "google.com", "microsoft.com", "store.steampowered.com" etc*)
> - Once done, make sure the _**I agree to the Steam Web API Terms of Use**_ checkbox is ticked and click **Register**

<p align="center">
   <img src="https://user-images.githubusercontent.com/77490730/217203552-2c33f315-598e-4b1b-88c5-aa658e9a0d52.png" width="60%">
</p>
<p align="center">
    <sub>Credit: <a href="https://cran.r-project.org/web/packages/CSGo/vignettes/auth.html">https://cran.r-project.org/</a></sub>
</p>

> - Copy the "Key" value, and paste it into the **API Key** box in Steam Achievement Notifier's **Settings** menu
> - Save the API Key to your configuration file by clicking the <img src="https://user-images.githubusercontent.com/77490730/217201647-5f603476-49ec-4036-a559-a25b2afdf09a.svg" width="16px" align="center"> icon

> STEAM64ID
> -
> - Go to https://steamid.io/lookup
> - Find your user profile - either by searching for your username, or pasting your Steam profile URL (*pictured*) and clicking the "lookup" button.

<p align="center">
   <img src="https://user-images.githubusercontent.com/77490730/217226759-8e593758-7441-4bc9-9d70-e389ca240ef5.png" width="60%">
</p>
<p align="center">
    <sub>If searching via account name, make sure it's actually your account (and not a similarly-named user alias)!</sub>
</p>

> - Make sure to copy the `steamid64` value ONLY (*if you add any other returned value, SAN will not be able to connect to the Steam Web API*)

<p align="center">
   <img src="https://user-images.githubusercontent.com/77490730/217227747-9b62b69e-84c5-4b49-a092-ad97528de30a.png" width="60%">
</p>
<p align="center">
    <sub>Do not copy the <code>steamID</code> or <code>steam3ID</code> values here!</sub>
</p>

> - Paste your copied `steam64id` value into the **Steam64 ID** box in Steam Achievement Notifier's **Settings** menu
> - Save the Steam64 ID to your configuration file by clicking the <img src="https://user-images.githubusercontent.com/77490730/217201647-5f603476-49ec-4036-a559-a25b2afdf09a.svg" width="16px" align="center"> icon

> GAME DETAILS
> -
> - In Steam Achievement Notifier's **Settings** menu, click the "_**Game Details must be set to Public**_" link below the **API Key**/**Steam64ID** boxes
> - This will open to Steam's Privacy settings page in the Steam client (*make sure Steam is open for this to work!*)
> - Make sure **Game Details** are set to **Public**, then click the **Save** button to apply your changes.

<p align="center">
    <img src="https://user-images.githubusercontent.com/77490730/217230888-5025ef6e-3f6f-45f0-838a-72f441546b9c.png" width="60%">
</p>
<p align="center">
    <sub>Credit: <a href="https://support.team17.com/hc/article_attachments/360004778117/mceclip0.png">https://support.team17.com/</a></sub>
</p>

As long as you have completed all of the above steps, Steam Achievement Notifier should be ready to go!

Thanks!

**Comment by SteamAchievementNotifier** [comment]
Hey again @bordeyishome,

I'll close this issue as the info you need is above. If you're still having issues, please open a new issue or join the Discord for further assistance!

Thanks!
