### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by leopardy2010** [SteamAchievementNotifier/SteamAchievementNotifier#39]
hi i dont know whats happening but when i try to open it loads and then never opens.
can i please have some help fixing it because i just downloded brand new and it was working fine i went to go get my api and it wouldnt open.

**Comment by SteamAchievementNotifier** [comment]
Hey @leopardy2010,

Firstly, check that the app isn't already running and just minimised to the system tray.

<p align="center">
    <img src="https://user-images.githubusercontent.com/77490730/217804180-69cdf54c-3fc6-4086-a185-a1d75c07c2fc.png" width="60%">
</p>

If the app isn't currently running, but still isn't opening, please try the following:

> Close Open Instances
> -
> - Open Task Manager, then click the **Details** tab
> - Find any instances of "**Steam Achievement Notifier (V1.84) Launcher**", *right-click* and select **End Task**
>
> Delete LocalAppData Folder
> -
> - Open the Start Menu, type `%localappdata%` and press *Enter*
> - In the folder that appears, find the `Steam Achievement Notifier (V1.8)` folder and delete it
>
> Restart the App
> -
> - Run **SANLauncherV1.84.exe** again to regenerate the required app files

If the app still won't open, try the following:

> Check the Console
> -
> - Click on the **SANLauncher splash screen** (to focus it), then press `CTRL` + `Shift` + `i` to open the **DevTools** panel
> - Click the `>>` icon (next to the `Elements` tab at the top of the **DevTools** panel)
> - Select `Console` in the dropdown menu
> - Check the **Console** tab for any errors that may be preventing the app from starting, and post a screenshot here.
<p align="center">
    <img src="https://user-images.githubusercontent.com/77490730/217801189-50873c41-a089-4056-b573-fa33c616f91a.png" width="60%">
</p>

Thanks!

**Comment by leopardy2010** [comment]
thanks turns out i needed to reset my computer then update the launcher and windows version for it

**Comment by SteamAchievementNotifier** [comment]
Hey again @leopardy2010,

Thanks for letting me know and I'm glad it's working now! Let me know if you have any further issues 👍

Thanks!
