### ISSUE TITLE
Steam Achievement Notifier Loading

### ISSUE THREAD

**Issue by hugsilv** [SteamAchievementNotifier/SteamAchievementNotifier#41]
Hey, So for some reason since yesterday everytime i open the exe it just stays Loading for ever and never opens

**Comment by SteamAchievementNotifier** [comment]
Hey @hugsilv,

If the app doesn't launch after running the EXE, please try the solution provided [here](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/issues/39), and let me know if you have any further issues.

Thanks!

**Comment by hugsilv** [comment]
I get this when i check the console 
![image](https://user-images.githubusercontent.com/62123080/227713440-c96aef6a-b844-446e-901a-6ae4533ff79e.png)

**Comment by hugsilv** [comment]
Ok its working. i deleted the folder in AppData/Local

**Comment by SteamAchievementNotifier** [comment]
Glad to hear it's working now! Please let me know if you have any further issues.

Thanks!
