### ISSUE TITLE
Achievement not showing

### ISSUE THREAD

**Issue by matdan2412** [SteamAchievementNotifier/SteamAchievementNotifier#43]
Hi everyone, I am encountering an issue with the app

My achievements are never showing, neither the Achievement Tracker or the Platinum Achievement
In the console it always shows a : "Failed to load resource: the server responded with a status of 400 ()"
Or a : "STEAM WEB API ERROR: TypeError: Cannot read properties of undefined (reading 'length'"

Thanks for reading, hoping we can find a solution (maybe I did something wrong ?)

![Achievement Bug](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/assets/113519009/7104c489-8398-4192-a4f5-a7eef8e5b7df)

**Comment by SteamAchievementNotifier** [comment]
Hey @matdan2412, apologies for the late response on this.

According to the [Steam Web API documentation](https://partner.steamgames.com/doc/webapi_overview/responses), a **400** error indicates a "Bad Request" - which means that it's likely that your API Key is either not valid or hasn't been saved to the app's config file.

To troubleshoot this, please check the following:

☑ **Click the Save Buttons**
◻ Make sure you have clicked the **Save** (💾) icon buttons to the right of the **API Key**/**Steam64ID** boxes after entering your details

☑ **Ensure Details Are Correct**
◻ Ensure your API Key is valid, and either re-enter it or generate a new one [here](https://steamcommunity.com/login/home/?goto=%2Fdev%2Fapikey)
◻ Ensure you have entered a valid Steam64ID (_e.g. When using [steamid.io](https://steamid.io/lookup) as suggested, make sure to copy the `steamid64` value - not any other value, such as `steam3id`_)

 > You can get your **API Key**/**Steam64 ID** values by clicking the buttons to the left of the corresponding text boxes in the Configuration menu
>
> ![image](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/assets/77490730/b918ed28-c82e-41f4-8d00-cd01bfba9c6b)

☑ **Check Game Details Are "Public"**
◻ Go to the [**Privacy Settings** page for your account](https://steamcommunity.com/id/undefined/edit/settings)

> Ensure that the **Game Details** setting here is set to `Public` (_otherwise, SAN will be unable to view achievement stats provided by the Steam Web API_)
>
> ![image](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/assets/77490730/4edf111a-1ee1-4e0d-92a6-72561b5efe93)

Let me know if you have any further issues with this after checking the above.

Thanks!

**Comment by matdan2412** [comment]
It seems that I just made a mistake when copy-pasting the Steam64ID (that I did multiple times ahahah, there was a caracter missing) sorry for the inconvenience and thank you for your help
Congratulations again for your work, this piece of software is really well made and is very satisfying to use
