### ISSUE TITLE
Sometimes, very randomly, powershell window pop ups for splti second and disappears.

### ISSUE THREAD

**Issue by WenexLJ** [SteamAchievementNotifier/SteamAchievementNotifier#5]
Not sure how else to describe it. I'm running the program in the background, everything works fine. But when I'm simply surfing on internet, reading or watching stuff, the powershell "window" will pop for a split second and disappear. I don't see anyone reporting this issue, so it must be on my end.

I guess the easiest workaround is to simply not have it constantly running in the background, but on other hand it's convinient for it always be, so I don't have to remember to launch it again. So if there is any way I can fix it myself, I would appreciate the help. If not then I will be waiting for some updates that hopefully fix that.

Also thanks for creating this! It's very cool it supports custom sound, as you can use anything you want. There's still slight delay between Steam Achivement popping and the sound itself, but it's still amazing. Personally I have windows notifications hidden, so I'm only using this program for sound and it's great.

Cheers.

**Comment by SteamAchievementNotifier** [comment]
Hey WenexLJ,

I am aware of this issue, but it seems to be a problem with Powershell itself, as described in [this issue](https://github.com/PowerShell/PowerShell/issues/3028) on the official Github page. It looks like there's no easy way to prevent the console window from showing briefly, even though the script specifies that it should not appear at all. This won't happen in-game, but will show outside of any game when the script restarts itself in the background (which was needed to fix another critical issue in the 1.4 release).

I looking into solutions provided in the linked issue to test whether this can be resolved for the 1.6 release. If not, I'll do my own research to get it fixed (as I personally find it kind of annoying as well).

A workaround until a fix is implemented would be to use a small third-party program called [Bill2's Process Manager](https://www.bill2-software.com/processmanager/download-en.shtml) to automatically start the app whenever you start a game (and close it when you quit). It has a portable option if you don't want to install it directly on your computer and is quite user-friendly. The only downside would be that you have to set up a rule for each game's .exe separately, and you would have to manually add another rule each time you buy/install a new game. I can provide instructions on how to set this up if you need.

And I'm really glad you like the app! There will be a slight delay as the API data is slower than the client, but I think it works well enough. But thanks a lot for downloading and trying it out.

Thanks!

**Comment by SteamAchievementNotifier** [comment]
Hey again WenexLJ,

Just to let you know, Version 1.6 (which will be released very soon) has resolved the console window issue, so please look out for the release within the next week or so.

Thanks!
