### ISSUE TITLE
when game is fullscrenn,achievement not show up

### ISSUE THREAD

**Issue by QJYEAH** [SteamAchievementNotifier/SteamAchievementNotifier#53]
could fix it？

**Comment by SteamAchievementNotifier** [comment]
Hey @QJYEAH,

I'll recap a bit here to help others who may have a similar question, but as discussed on Discord, notifications cannot currently be shown over games set to "Fullscreen" mode when using **Direct X 9**/**10**/**11**, **Vulkan** or **OpenGL** graphics APIs.

> ℹ️ However, notifications *may* be able to show over modern games that use **Direct X 12** and that are set to "Fullscreen" mode (*not "Exclusive Fullscreen"*), but YMMV.

I'll be looking into a solution for this further down the line, so make sure to check back for future updates.

Thanks!
