### ISSUE TITLE
only notification sound

### ISSUE THREAD

**Issue by gatongato** [SteamAchievementNotifier/SteamAchievementNotifier#55]
Hello, I have a problem with the application. I only hear the notification sound, but it is not displayed on the screen. I have the steam overlay disabled, the game is FFVII Remake version Dx11 exclusive full screen mode. Thanks for the app!

**Comment by SteamAchievementNotifier** [comment]
Hey @gatongato,

Please see #53 - Fullscreen is not currently supported.

Thanks!
