### ISSUE TITLE
[Bug] The Deck preset is misaligned in the screenshots.

### ISSUE THREAD

**Issue by DomBui** [SteamAchievementNotifier/SteamAchievementNotifier#57]
The notification overlay itself is fine, but the overlay is misaligned and cut off in the screenshots. I'm using 2560x1440 resolution.

I was using the top right position in this screenshot.

![Trial-and-Error](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/assets/17226514/d20d1f22-919a-4c80-a167-ea02951061c3)

The second image is from testing with CTRL + SHIFT + 3 using top center. It's the same for all positions.

![100% Complete](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/assets/17226514/333e4a57-3d8a-4ea3-be58-26ebcf7c8688)

**Comment by SteamAchievementNotifier** [comment]
Hey @DomBui,

The notification size has been changed in V1.9.4 to accommodate the new Customiser options, so that's likely the reason for this issue. I'll be looking into a fix for the next release 👍

Thanks!

**Comment by SteamAchievementNotifier** [comment]
Hey @DomBui,

V1.9.5 has now been released, which resolves this issue 👍 I'll close this, but let me know if you have any further issues atfer updating.

Thanks!
