### ISSUE TITLE
Question: Does this app display a notification when a game finds a match?

### ISSUE THREAD

**Issue by cauamachado51** [SteamAchievementNotifier/SteamAchievementNotifier#58]
(title) ChatGPT monica talked about this app when I was researching it, I've already entered half-baked matches because I was watching YouTube, DBD (Dead By Daylight) has a long waiting time in the killer queue.

**Comment by SteamAchievementNotifier** [comment]
Hey @cauamachado51 ,

This app shows Steam achievement notifications. It doesn't have any access to any game's internal engine, so it doesn't have access to in-game events for any game. So unfortunately, it won't be suitable for what you're looking for.

AFAIK, the only way this would be possible is for someone to create a mod for that specific game, but SAN isn't designed to be a general-purpose notification system, meaning it also wouldn't be compatible with any existing game-specific mods. It may be worth looking around for DBD mod content online or finding Discord communities etc.

Thanks!

**Comment by cauamachado51** [comment]
> Hey @cauamachado51 ,
> 
> This app shows Steam achievement notifications. It doesn't have any access to any game's internal engine, so it doesn't have access to in-game events for any game. So unfortunately, it won't be suitable for what you're looking for.
> 
> AFAIK, the only way this would be possible is for someone to create a mod for that specific game, but SAN isn't designed to be a general-purpose notification system, meaning it also wouldn't be compatible with any existing game-specific mods. It may be worth looking around for DBD mod content online or finding Discord communities etc.
> 
> Thanks!

thanks for the response
