### ISSUE TITLE
[Request] Option to disable on-screen overlay and exclusively push to the External Window

### ISSUE THREAD

**Issue by ajsglist** [SteamAchievementNotifier/SteamAchievementNotifier#63]
Hi there,

The External Window provides extremely valuable use cases for me, and it would be great to have the option to exclusively output achievement notifications to this external window without any output on top of the game directly.

Thanks for the consideration.

edit: quick screenshot in case disambiguation is desired

![image](https://github.com/user-attachments/assets/8b03d26f-b0ef-4edc-a7fe-719cc9f2c018)

**Comment by SteamAchievementNotifier** [comment]
Hey @ajsglist ,

As there's no direct way to hide the actual notification (outside of enabling **Sound-Only Mode**) while keeping the external window active, a workaround for this would be to enable the **Use Custom Position** option and place the notification somewhere offscreen.

This would fulfil three requirement to keep the notification hidden but allowing the external window to remain visible.

> FYI, V1.85 has now been superceded by V1.9 (although the **Duplicate to External Window** option has changed slightly in the newer version, but should provide the same functionality). This means that any version below V1.85 won't be receiving any further updates, so any suggestions for new features will only be applicable to V1.9 and above.

Thanks!

**Comment by SteamAchievementNotifier** [comment]
Hey again @ajsglist ,

Basically, while it would be possible, it's not something that I'm looking to add any time soon, as there's lots of other things that I'm looking to add in upcoming updates - hence the suggestion to "hide" it using the **Use Custom Position** option as a workaround for the time being.

Another option - if you're willing to add a line of code - is to enable the **Use Custom App Files** option, and add CSS to prevent the notification from appearing, although I appreciate that this may not be ideal if you don't have any coding experience.

If I get any time to do so, I'll consider adding it as a new option, but I can't guarantee that this will be within any sort of immediate timeframe.

Thanks!

**Comment by ajsglist** [comment]
Can you elaborate on the custom CSS required to prevent the notification

Thanks.

**Comment by SteamAchievementNotifier** [comment]
Hey again @ajsglist,

I've provided an edited version of `base.css` which hides all notifications:

> - [Download this ZIP file](https://github.com/user-attachments/files/16201815/base.zip) and extract `base.css` within it.
> - Enable **Use Custom App Files**, then click the **Show Custom App Files** button (*This will open `C:\Users\%username%\AppData\Local\Steam Achievement Notifier (V1.9)\customfiles`*)
> 
> ![image](https://github.com/user-attachments/assets/3885e5ee-7cd1-4cc6-a51c-f5336391bbe6)
> 
> - Open the `notify` folder and rename/delete the existing `base.css` file, then replace it with the new file

Once you trigger a test notification, you shouldn't see it on-screen anymore.

Thanks!
