### ISSUE TITLE
Plans for SteamDeck / SteamOS

### ISSUE THREAD

**Issue by joeblack2k** [SteamAchievementNotifier/SteamAchievementNotifier#65]
Are there any plans to implant this into Gamescope? SteamOS? Perhaps a plugin deckyloader? This would make the ultimate home console imho

**Comment by SteamAchievementNotifier** [comment]
Hey @joeblack2k ,

Some users have already been able to run the available AppImage on SteamDeck, but as I don't have one myself, I don't have any way of verifying compatibility outside of VMs (which aren't 1:1 with SteamOS anyway), so YMMV.

Linux isn't my main OS, so it's very much what-you-see-is-what-you-get and will probably remain that way in all honesty. I'm happy for more Linux-experienced devs to fork the project and incorporate into these things, but as it stands, the app will probably remain targeting desktops first and foremost, and if it's ever possible to fully emulate SteamDeck on desktop, I'll look into it.

Thanks!
