### ISSUE TITLE
Games slowing down when getting an achievement

### ISSUE THREAD

**Issue by Sobitax** [SteamAchievementNotifier/SteamAchievementNotifier#66]
Random games (The werecleaner and Maniac) slow down when getting an achievement.

**Comment by SteamAchievementNotifier** [comment]
Hey @Sobitax ,

What are your specs? Some people have had success with enabling the **Disable Hardware Acceleration** option when notifications cause slowdown, so might be worth testing to see if it improves things if you haven't done so already.

Outside of that, I've noticed that using frame generation software (like Lossless Scaling) will reduce the game's FPS to the non-FG value while the notification is on-screen, but not sure if you're using anything like that for the affected games.

Let me know if this improves things.

Thanks!
