### ISSUE TITLE
Feature Request - Add Ability to send Webhook Request on Achievement 

### ISSUE THREAD

**Issue by Z0y6h0kS9X** [SteamAchievementNotifier/SteamAchievementNotifier#67]
Are there any plans to implement the ability to send a webhook when an achievement is unlocked?  It would be nice to send a message to slack/discord/3rd party tracking app when an achievement is unlocked.

**Comment by SteamAchievementNotifier** [comment]
Hey @Z0y6h0kS9X,

I had the idea to add the ability to send achievement info via webhooks a long time ago but never implemented it into the app. It is something that I want to add, so I'll look into it for a future release.

Thanks!

**Comment by SteamAchievementNotifier** [comment]
Hey again @Z0y6h0kS9X,

This has been added and will be available in the upcoming V1.9.8 release. I'm still fixing some general bugs before pushing the new update, but it should be available relatively soon.

Thanks!
