### ISSUE TITLE
A breakpoint has been reached

### ISSUE THREAD

**Issue by DrexlSpivey** [SteamAchievementNotifier/SteamAchievementNotifier#68]
Sometimes when shutting down Windows (11) I get the following message:

![IMG_20240816_165123](https://github.com/user-attachments/assets/41995590-0e28-4abf-acfa-90d019f783e8)

**Comment by SteamAchievementNotifier** [comment]
Hey @DrexlSpivey,

I've added a potential fix for this in the upcoming V1.9.8 release. It will be available relatively soon, but let me know whether you still get this error appear once the update is live.

Thanks!

**Comment by DrexlSpivey** [comment]
Sure, I'll tell you if I encounter it again.
