### ISSUE TITLE
When a game is closed, the app fails to release it if there is an update available.

### ISSUE THREAD

**Issue by fantasygone** [SteamAchievementNotifier/SteamAchievementNotifier#72]
### Has this issue previously been reported?

- [X] This issue has not been previously reported

### Platform

Windows

### Version

Last 2 versions before V1.9.14

### Bug Details

SAN (Steam Achievement Notifier app) has been accurately detecting when I close games lately, except for a few instances.

Whenever this issue occurs and I open SAN, I consistently see a pop-up about an update that needs to be downloaded. This leads me to believe that the pop-up is triggered before the game closure is processed, and the app never gets past it.

Is this behavior intentional to draw attention to updates, or could it be an error? It's happening fairly frequently.

### If possible, provide steps to reproduce the bug

1) Run the game
2) Release a new update (not sure if before or while the game is running has an impact)
3) Close the game

Game is not released because there is an update

**Comment by SteamAchievementNotifier** [comment]
Hey @fantasygone ,

Thanks for the report. I'll test this out and see if I can replicate.

And as much as I would like users to always update to the latest version, this behaviour is not intentional. The aim is to keep SAN in a working state regardless of version, so it's not something that has been intentionally implemented to force that.

Thanks!

**Comment by fantasygone** [comment]
Super, thanks.

> And as much as I would like users to always update to the latest version, this behaviour is not intentional.And as much as I would like users to always update to the latest version, this behaviour is not intentional.

I figured as much. Unless the update is very very important it should not get in the way of its functions. Hopefully you find a fix soon!

**Comment by SteamAchievementNotifier** [comment]
Hey again @fantasygone,

I've tested this and I can't replicate the behaviour you're describing. Games are detected and released in the same way they are when no update is available.

If you have any errors appearing in **Settings** > **App Log** when this issue occurs, please provide them. Otherwise, it seems like it may be a specific game or local system issue.

Thanks!

**Comment by fantasygone** [comment]
It keeps happening...

**Comment by SteamAchievementNotifier** [comment]
Hey again @fantasygone,

As previously stated, I can't replicate the issue my side, so if there are any errors appearing, I'll need your **App Log** after the issue has occurred to assist. Otherwise, sounds like it's a game-specific or local issue, so obviously, there's not much I can do to help in that case.

Thanks!

**Comment by fantasygone** [comment]
`[22/12/2024 23:15:15]
[APP]: INFO
"rust.log" created successfully 

[22/12/2024 23:15:15]
[APP]: INFO
"APP" process created 

[22/12/2024 23:15:16]
[APP]: INFO
"C:\Users\coron\AppData\Local\Steam Achievement Notifier (V1.9)" already exists: No changes were made 

[22/12/2024 23:15:16]
[APP]: INFO
"C:\Users\coron\AppData\Local\Steam Achievement Notifier (V1.9)\customfiles" Package Version (1.9.16) is outdated compared to current App Version (1.9.18): Attempting backup... 

[22/12/2024 23:15:16]
[APP]: INFO
"C:\Users\coron\AppData\Local\Steam Achievement Notifier (V1.9)\customfiles_V1.9.16" backup directory created successfully 

[22/12/2024 23:15:17]
[APP]: INFO
"C:\Users\coron\AppData\Local\Programs\steamachievementnotifierv1.9\resources\app.asar" copied to "C:\Users\coron\AppData\Local\Steam Achievement Notifier (V1.9)\customfiles" successfully 

[22/12/2024 23:15:17]
[MAIN]: INFO
"MAIN" process created 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"webhookmain" missing in config 

[22/12/2024 23:15:17]
[MAIN]: INFO
"webhookmain" written to config successfully 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"webhookrare" missing in config 

[22/12/2024 23:15:17]
[MAIN]: INFO
"webhookrare" written to config successfully 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"webhookplat" missing in config 

[22/12/2024 23:15:17]
[MAIN]: INFO
"webhookplat" written to config successfully 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"webhookspoilers" missing in config 

[22/12/2024 23:15:17]
[MAIN]: INFO
"webhookspoilers" written to config successfully 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"statwinshortcut" missing in config 

[22/12/2024 23:15:17]
[MAIN]: INFO
"statwinshortcut" written to config successfully 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"statwinaot" missing in config 

[22/12/2024 23:15:17]
[MAIN]: INFO
"statwinaot" written to config successfully 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"ssdisplay" missing in "customisation.main" 

[22/12/2024 23:15:17]
[MAIN]: INFO
"ssdisplay" written to "customisation.main" successfully 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"iconanim" missing in "customisation.main" 

[22/12/2024 23:15:17]
[MAIN]: INFO
"iconanim" written to "customisation.main" successfully 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"ssdisplay" missing in "customisation.rare" 

[22/12/2024 23:15:17]
[MAIN]: INFO
"ssdisplay" written to "customisation.rare" successfully 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"ssdisplay" missing in "customisation.plat" 

[22/12/2024 23:15:17]
[MAIN]: INFO
"ssdisplay" written to "customisation.plat" successfully 

[22/12/2024 23:15:17]
[MAIN]: INFO
Steam installation path: c:/program files (x86)/steam 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"ssdisplay" missing in "customisation.main.usertheme.0.customisation" 

[22/12/2024 23:15:17]
[MAIN]: INFO
"ssdisplay" written to "customisation.main.usertheme.0.customisation" successfully 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"iconanim" missing in "customisation.main.usertheme.0.customisation" 

[22/12/2024 23:15:17]
[MAIN]: INFO
"iconanim" written to "customisation.main.usertheme.0.customisation" successfully 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"ssdisplay" missing in "customisation.main.usertheme.1.customisation" 

[22/12/2024 23:15:17]
[MAIN]: INFO
"ssdisplay" written to "customisation.main.usertheme.1.customisation" successfully 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"iconanim" missing in "customisation.main.usertheme.1.customisation" 

[22/12/2024 23:15:17]
[MAIN]: INFO
"iconanim" written to "customisation.main.usertheme.1.customisation" successfully 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"ssdisplay" missing in "customisation.rare.usertheme.0.customisation" 

[22/12/2024 23:15:17]
[MAIN]: INFO
"ssdisplay" written to "customisation.rare.usertheme.0.customisation" successfully 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"ssdisplay" missing in "customisation.rare.usertheme.1.customisation" 

[22/12/2024 23:15:17]
[MAIN]: INFO
"ssdisplay" written to "customisation.rare.usertheme.1.customisation" successfully 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"ssdisplay" missing in "customisation.plat.usertheme.0.customisation" 

[22/12/2024 23:15:17]
[MAIN]: INFO
"ssdisplay" written to "customisation.plat.usertheme.0.customisation" successfully 

[22/12/2024 23:15:17]
[MAIN]: ERROR
"ssdisplay" missing in "customisation.plat.usertheme.1.customisation" 

[22/12/2024 23:15:17]
[MAIN]: INFO
"ssdisplay" written to "customisation.plat.usertheme.1.customisation" successfully 

[22/12/2024 23:15:17]
[RENDERER]: INFO
"VNaN" dir detected and removed successfully 

[22/12/2024 23:15:17]
[RENDERER]: INFO
"RENDERER" process created 

[22/12/2024 23:15:18]
[MAIN]: INFO
"C:\Users\coron\AppData\Local\Programs\steamachievementnotifierv1.9\resources\temp" directory cleared successfully 

[22/12/2024 23:15:18]
[MAIN]: INFO
No running game or "Worker" processes found. Restarting "Worker" process... 

[22/12/2024 23:15:18]
[RENDERER]: INFO
[AUTOUPDATER]: Checking for update... 

[22/12/2024 23:15:18]
[RENDERER]: ERROR
Monitor "id" (2528732444) not found in previous "monitors" object for "monitor" in config 

[22/12/2024 23:15:18]
[RENDERER]: INFO
Successfully updated "monitors" array 

[22/12/2024 23:15:19]
[RENDERER]: INFO
[AUTOUPDATER]: Latest version installed (V1.9.18) 

[22/12/2024 23:15:20]
[WORKER]: INFO
"WORKER" process created 

[22/12/2024 23:15:20]
[WORKER]: INFO
Idle loop started 

`

**Comment by fantasygone** [comment]
Was the log unhelpful?

**Comment by SteamAchievementNotifier** [comment]
Hey again @fantasygone ,

Apologies for the late response. The log seems to indicate that you've now updated to V1.9.18 - which is the latest version - so unfortunately, it doesn't help in this scenario.

If it happens again with the next release, please send your App Log before updating to the latest version.

Thanks!
